<?php

/**
 * @file
 * Functions to support theming.
 */

/**
 * Implements hook_preprocess_image_widget().
 */
function sr_theme_preprocess_image_widget(array &$variables): void {
  $data = &$variables['data'];

  // This prevents image widget templates from rendering preview container HTML
  // to users that do not have permission to access these previews.
  // @todo revisit in https://drupal.org/node/953034
  // @todo revisit in https://drupal.org/node/3114318
  if (isset($data['preview']['#access']) && $data['preview']['#access'] === FALSE) {
    unset($data['preview']);
  }
}


/**
 * Passes data to block template.
 */
function stever_preprocess_block(&$variables) {
  // Check if the block is the one you want to modify.
  if ($variables['plugin_id'] == 'hello_world_block') {
	  // Pass the block title to the block template.
	  $variables['block_title'] = $variables['label'];
  }
}